# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: RearrangeDataset-v0
split: eval
data_path: data/datasets/perception/perception_eval.json.gz
scenes_dir: "data/scene_datasets/hssd-hab"
