# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: task_config_base

  - /habitat/simulator/agents/habitat_mas_agents@habitat.simulator.agents.agent_0: SpotRobot_default
  - /habitat/simulator/agents/habitat_mas_agents@habitat.simulator.agents.agent_1: DJIDrone_default
  - /habitat/simulator/agents/habitat_mas_agents@habitat.simulator.agents.agent_2: FetchRobot_default
  - /habitat/simulator/agents/habitat_mas_agents@habitat.simulator.agents.agent_3: StretchRobot_default

  - /habitat/dataset/embodied_mas: zxz_manipulation

  - /habitat/task/actions@habitat.task.actions.agent_0_arm_pick_action: arm_pick_action
  - /habitat/task/actions@habitat.task.actions.agent_0_arm_place_action: arm_place_action
  - /habitat/task/actions@habitat.task.actions.agent_0_base_velocity: base_velocity_non_cylinder
  - /habitat/task/actions@habitat.task.actions.agent_0_rearrange_stop: rearrange_stop
  - /habitat/task/actions@habitat.task.actions.agent_0_pddl_apply_action: pddl_apply_action
  - /habitat/task/actions@habitat.task.actions.agent_0_oracle_nav_action: spot_oracle_nav_action
  - /habitat/task/actions@habitat.task.actions.agent_0_arm_reset_action: arm_reset_action
  - /habitat/task/actions@habitat.task.actions.agent_0_wait: wait

  - /habitat/task/actions@habitat.task.actions.agent_1_base_velocity: drone_base_velocity
  - /habitat/task/actions@habitat.task.actions.agent_1_rearrange_stop: rearrange_stop
  - /habitat/task/actions@habitat.task.actions.agent_1_pddl_apply_action: pddl_apply_action
  - /habitat/task/actions@habitat.task.actions.agent_1_oracle_nav_action: drone_oracle_nav_action
  - /habitat/task/actions@habitat.task.actions.agent_1_wait: wait

  - /habitat/task/actions@habitat.task.actions.agent_2_arm_pick_action: arm_pick_action
  - /habitat/task/actions@habitat.task.actions.agent_2_arm_place_action: arm_place_action
  - /habitat/task/actions@habitat.task.actions.agent_2_base_velocity: base_velocity_non_cylinder
  - /habitat/task/actions@habitat.task.actions.agent_2_rearrange_stop: rearrange_stop
  - /habitat/task/actions@habitat.task.actions.agent_2_pddl_apply_action: pddl_apply_action
  - /habitat/task/actions@habitat.task.actions.agent_2_oracle_nav_action: fetch_oracle_nav_action
  - /habitat/task/actions@habitat.task.actions.agent_2_arm_reset_action: arm_reset_action
  - /habitat/task/actions@habitat.task.actions.agent_2_wait: wait

  - /habitat/task/actions@habitat.task.actions.agent_3_arm_pick_action: arm_pick_action
  - /habitat/task/actions@habitat.task.actions.agent_3_arm_place_action: arm_place_action
  - /habitat/task/actions@habitat.task.actions.agent_3_base_velocity: base_velocity_non_cylinder
  - /habitat/task/actions@habitat.task.actions.agent_3_rearrange_stop: rearrange_stop
  - /habitat/task/actions@habitat.task.actions.agent_3_pddl_apply_action: pddl_apply_action
  - /habitat/task/actions@habitat.task.actions.agent_3_oracle_nav_action: stretch_oracle_nav_action
  - /habitat/task/actions@habitat.task.actions.agent_3_arm_reset_action: arm_reset_action
  - /habitat/task/actions@habitat.task.actions.agent_3_wait: wait

  - /habitat/task/measurements:
    - pddl_success
    - num_steps
    - did_agents_collide
    - num_agents_collide
    - composite_stage_goals
    - pddl_subgoal_reward
    - rearrange_cooperate_reward
  - /habitat/task/lab_sensors:
    - relative_resting_pos_sensor
    - target_start_sensor
    - goal_sensor
    - joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - target_start_gps_compass_sensor
    - target_goal_gps_compass_sensor
    - localization_sensor
    #- other_agent_gps
    - detected_objects_sensor
    - pddl_text_goal
    #- arm_workspace_rgb_sensor
    #- object_masks_sensor
    #- nav_workspace_rgb_sensor
    #- arm_workspace_points_sensor
    #- nav_workspace_points_sensor
  - /habitat/task/lab_sensors@habitat.task.lab_sensors.agent_0_agents_within_threshold: agents_within_threshold
  - /habitat/task/lab_sensors@habitat.task.lab_sensors.agent_1_agents_within_threshold: agents_within_threshold
  - /habitat/task/lab_sensors@habitat.task.lab_sensors.agent_2_agents_within_threshold: agents_within_threshold
  - /habitat/task/lab_sensors@habitat.task.lab_sensors.agent_3_agents_within_threshold: agents_within_threshold
  - _self_

habitat:
  task:
    lab_sensors:
      agent_0_agents_within_threshold:
        x_len: 2.0
        y_len: 1.5
        agent_idx: 0
      agent_1_agents_within_threshold:
        x_len: 2.0
        y_len: 1.5
        agent_idx: 1
      agent_2_agents_within_threshold:
        x_len: 2.0
        y_len: 1.5
        agent_idx: 2
      agent_3_agents_within_threshold:
        x_len: 2.0
        y_len: 1.5
        agent_idx: 3
    type: RearrangePddlTask-v0
    reward_measure: rearrange_cooperate_reward
    success_measure: pddl_success
    success_reward: 10.0
    min_distance_start_agents: 5.0
    slack_reward: -0.0005
    end_on_success: True
    constraint_violation_ends_episode: False
    constraint_violation_drops_object: True
    measurements:
      pddl_success:
        must_call_stop: False
      rearrange_cooperate_reward:
        stage_sparse_reward: 5.0
        end_on_collide: True
        collide_penalty: 0.5
    task_spec_base_path: benchmark/multi_agent/
    task_spec: pddl/zxz_multi_agent_man
    pddl_domain_def: fp
    robot_at_thresh: 3.0

  environment:
    max_episode_steps: 750
  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
      - "data/objects/amazon_berkeley/configs/"
      - "data/objects/google_object_dataset/configs/"
    concur_render: True
    auto_sleep: True
    agents_order:
      - agent_0
      - agent_1
      - agent_2
      - agent_3

    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False

    habitat_sim_v0:
      allow_sliding: True
      enable_physics: True
    agents:
      agent_0:
        joint_start_noise: 0.0
      agent_2:
        joint_start_noise: 0.0
      agent_3:
        joint_start_noise: 0.0
  dataset:
    data_path: data/datasets/replica_cad/multi_agent_eval.json.gz
    # new
    randomize_agent_start: 1
    # TODO
    robot_config: data/robots/robot_configs/replica_cad/multi_agent_eval.json
    mode: manipulation
